server_ip: "127.0.0.2"
server_port: 7080
client_ip: "127.0.0.3"
client_port_lower: 32768
client_port_upper: 60999
protocol_id: 6
preferred_mss: 1440
window_scale: 14
window_size_with_scale: 12800
keepalive_interval: 5
idle_timeout: 25
max_keepalive_attempts: 3
keep_alive_enabled: true
packet_lost_simulation: true
max_resend_count: 5
resend_interval: 200
sack_permit_support: true
sack_option_support: true